language: node_js
node_js:
  - "10"
cache: yarn
before_install: yarn lint
before_script: yarn test
script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: master
  local-dir: dist
  fqdn: blog.wenshengchen.com
  project-name: Blog
